---
title: "Linear Regression in the Machine Learning Universe"
output: html_notebook
---

##Loading Data

```{r}
library(HistData)
library(tidyverse)
galton_heights <- GaltonFamilies%>%
  filter(childNum == 1 & gender == "male")%>%
  select(father, childHeight)%>%
  rename(son = childHeight)

```
## Generate Test and Train sets

```{r}
library(caret)
y <- galton_heights$son
test_index <- createDataPartition(y, times = 1, p = 0.5, list = F)
train_set <- galton_heights %>%
  slice(-test_index)
test_set <- galton_heights%>%
  slice(test_index)
```

##Predict Function
```{r}
fit <- lm(son ~father, data = train_set)
fit$coefficients
y_hat <- predict(fit, test_set)
mean((y_hat-test_set$son)^2)
```

#Comprehension Chck: Logistic Regression

```{r}
library(caret)
library(tidyverse)
set.seed(2)
make_data <- function(n = 1000, p = 0.5, 
				mu_0 = 0, mu_1 = 2, 
				sigma_0 = 1,  sigma_1 = 1){

y <- rbinom(n, 1, p)
f_0 <- rnorm(n, mu_0, sigma_0)
f_1 <- rnorm(n, mu_1, sigma_1)
x <- ifelse(y == 1, f_1, f_0)
  
test_index <- createDataPartition(y, times = 1, p = 0.5, list = FALSE)

list(train = data.frame(x = x, y = as.factor(y)) %>% slice(-test_index),
	test = data.frame(x = x, y = as.factor(y)) %>% slice(test_index))
}
dat <- make_data()

dat$train %>% ggplot(aes(x, color = y)) + geom_density()
set.seed(345634925)
delta <- seq(0, 3, len=25)
g <- 0
f <- 1
for (i in seq(0, 3, len=25)) {
  da <- make_data(mu_1 = i)
  als <- glm(y ~ x, family = "binomial", data = da$train)
  coco <- predict(als, newdata = da$test) ##TAVA ERRANDO AQUI!!! É NEWDATA E NÃO DATA PORRRAAAAA!!!!!!!
  y_hat <- ifelse(coco > 0.5, 1,0)%>%
    factor(levels = c(0,1))
  g[f] = mean(y_hat == da$test$y)
  f = f+1
}
summary(reference)
delta <- data.frame(delta, g)
ggplot(data = delta, aes(delta, g))+geom_point()

#Resposta:
set.seed(1)
delta <- seq(0, 3, len = 25)
res <- sapply(delta, function(d){
	dat <- make_data(mu_1 = d)
	fit_glm <- dat$train %>% glm(y ~ x, family = "binomial", data = .)
	y_hat_glm <- ifelse(predict(fit_glm, dat$test) > 0.5, 1, 0) %>% factor(levels = c(0, 1))
	mean(y_hat_glm == dat$test$y)
})
qplot(delta, res)

  View(da$test)
  y_hat
```
